services:
  
  db:
    image: postgres:17
    container_name: inventory_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  flyway:
    image: flyway/flyway:9.21.1
    container_name: inventory_flyway
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migration:/flyway/sql   # Mount migration scripts
    
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_BASELINE_ON_MIGRATE=true
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql
    command: migrate
 
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory_api
    ports:
      - "5180:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  pgdata: