services:
  db:
    image: postgres:17
    container_name: inventory_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
 # this is a test
  liquibase:
    image: liquibase/liquibase:latest
    depends_on:
      - db
    volumes:
      - ./liquibase:/liquibase
    working_dir: /liquibase
    command: ["update"]  # default command, can be overridden
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory_api
    ports:
      - "5180:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata: