# name: Run Compose

# on: [push]

# jobs:
#   run-compose:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4
        
#       - name: Run docker compose
#         run: docker compose up -d
#         env:
#           POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
#           POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
#           POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
#           CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}